# Generated by Django 3.0.2 on 2020-01-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
